### ISSUE TITLE
error using stringbuilder even after it being installed.

### ISSUE THREAD

**Issue by project2harsh** [delmosaurio/stringbuilder#5]
> var stringbuilder = require("/stringbuilder/lib/stringbuilder");
Error: Cannot find module '/stringbuilder/lib/stringbuilder'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by gidhin** [comment]
Even i have the same issue after installed
